name: Build and Publish WASM
on:
  push: 
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:    
env:
  PLATFORM: PLATFORM_WEB
  GITHUB_SHA: ${{ github.sha }}
  REPO: ${{ github.repository }}  
jobs:
  make-gh-pages:
    name: Create gh-pages branch if necessary
    runs-on: ubuntu-latest
    steps:
      - name: Create gh-pages branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'gh-pages'
  build:
    name: Build WASM for Merge
    needs: [make-gh-pages]    
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout raylib-game-template
        uses: actions/checkout@v3
        with:
          path: raylib-game-template
      -
        name: Docker Build
        run: ./raylib-game-template/docker-scripts/docker-build.sh
      -
        name: Docker Run
        run: ./raylib-game-template/docker-scripts/docker-run.sh
      - 
        name: Zip release artifacts
        run: ./raylib-game-template/docker-scripts/zip-files.sh
      - 
        name: Deploy Static Site
        uses: moodiest/push-to-branch-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: raylib-game-template/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}